# Generated by Django 4.1.2 on 2023-02-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('FedId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FederationName', models.TextField(max_length=100)),
                ('PresidentName', models.TextField(max_length=60)),
                ('PresidentLastName', models.TextField(max_length=60)),
                ('PresidentEmail', models.TextField(max_length=80)),
                ('PresidentPhone', models.TextField(max_length=15)),
                ('ContactPersonName', models.TextField(max_length=60)),
                ('ContactPersonLastName', models.TextField(max_length=60)),
                ('ContactPersonPosition', models.TextField(max_length=60)),
                ('Email', models.TextField(max_length=80)),
                ('Phone', models.TextField(max_length=15)),
                ('AddedDate', models.DateTimeField()),
                ('yearUpdate', models.CharField(max_length=4)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('DistrictId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('DistrictName', models.TextField(max_length=80)),
                ('Participation', models.CharField(default='No', max_length=3)),
                ('FormalStructure', models.CharField(default='No', max_length=3)),
                ('ContactPersonName', models.TextField(max_length=80)),
                ('ContactPersonLastName', models.TextField(max_length=80)),
                ('Phone', models.TextField(max_length=15)),
                ('Email', models.TextField(max_length=80)),
                ('DistrictOrProvince', models.TextField(max_length=30)),
                ('NoStructureReason', models.TextField(max_length=150)),
                ('NumberOfClubs', models.IntegerField()),
                ('AddDate', models.DateTimeField()),
                ('Federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
