# Generated by Django 4.1.2 on 2023-02-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FedInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='Federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FedInfo.federation'),
        ),
        migrations.AlterField(
            model_name='district',
            name='NoStructureReason',
            field=models.TextField(default='Note stated', max_length=150),
        ),
    ]
